# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnFirebaseNotification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnFirebaseNotification
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  target 'rnFirebaseNotification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rnFirebaseNotificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
